// utils/currencyCountryMap.js

const currencyCountryMap = {
  // Main currencies with clear country codes
  USD: { name: 'United States Dollar', countryCode: 'US' },
  AED: { name: 'Emirati Dirham', countryCode: 'AE' },
  AFN: { name: 'Afghan Afghani', countryCode: 'AF' },
  ALL: { name: 'Albanian Lek', countryCode: 'AL' },
  AMD: { name: 'Armenian Dram', countryCode: 'AM' },
  ANG: { name: 'Dutch Guilder', countryCode: 'NL' },
  AOA: { name: 'Angolan Kwanza', countryCode: 'AO' },
  ARS: { name: 'Argentine Peso', countryCode: 'AR' },
  AUD: { name: 'Australian Dollar', countryCode: 'AU' },
  AWG: { name: 'Aruban Florin', countryCode: 'AW' },
  AZN: { name: 'Azerbaijani Manat', countryCode: 'AZ' },
  BAM: { name: 'Bosnia-Herzegovina Convertible Mark', countryCode: 'BA' },
  BBD: { name: 'Barbadian Dollar', countryCode: 'BB' },
  BDT: { name: 'Bangladeshi Taka', countryCode: 'BD' },
  BGN: { name: 'Bulgarian Lev', countryCode: 'BG' },
  BHD: { name: 'Bahraini Dinar', countryCode: 'BH' },
  BIF: { name: 'Burundian Franc', countryCode: 'BI' },
  BMD: { name: 'Bermudan Dollar', countryCode: 'BM' },
  BND: { name: 'Brunei Dollar', countryCode: 'BN' },
  BOB: { name: 'Bolivian Boliviano', countryCode: 'BO' },
  BRL: { name: 'Brazilian Real', countryCode: 'BR' },
  BSD: { name: 'Bahamian Dollar', countryCode: 'BS' },
  BTN: { name: 'Bhutanese Ngultrum', countryCode: 'BT' },
  BWP: { name: 'Botswanan Pula', countryCode: 'BW' },
  BYN: { name: 'Belarusian Ruble', countryCode: 'BY' },
  BZD: { name: 'Belize Dollar', countryCode: 'BZ' },
  CAD: { name: 'Canadian Dollar', countryCode: 'CA' },
  CDF: { name: 'Congolese Franc', countryCode: 'CD' },
  CHF: { name: 'Swiss Franc', countryCode: 'CH' },
  CLP: { name: 'Chilean Peso', countryCode: 'CL' },
  CNY: { name: 'Chinese Yuan', countryCode: 'CN' },
  COP: { name: 'Colombian Peso', countryCode: 'CO' },
  CRC: { name: 'Costa Rican Colon', countryCode: 'CR' },
  CUP: { name: 'Cuban Peso', countryCode: 'CU' },
  CVE: { name: 'Cape Verdean Escudo', countryCode: 'CV' },
  CZK: { name: 'Czech Republic Koruna', countryCode: 'CZ' },
  DJF: { name: 'Djiboutian Franc', countryCode: 'DJ' },
  DKK: { name: 'Danish Krone', countryCode: 'DK' },
  DOP: { name: 'Dominican Peso', countryCode: 'DO' },
  DZD: { name: 'Algerian Dinar', countryCode: 'DZ' },
  EGP: { name: 'Egyptian Pound', countryCode: 'EG' },
  ERN: { name: 'Eritrean Nakfa', countryCode: 'ER' },
  ETB: { name: 'Ethiopian Birr', countryCode: 'ET' },
  EUR: { name: 'Euro', countryCode: 'EU' }, // EU for Eurozone
  FJD: { name: 'Fijian Dollar', countryCode: 'FJ' },
  FKP: { name: 'Falkland Islands Pound', countryCode: 'FK' },
  FOK: { name: 'Faroese Króna', countryCode: 'FO' },
  GBP: { name: 'British Pound Sterling', countryCode: 'GB' },
  GEL: { name: 'Georgian Lari', countryCode: 'GE' },
  GGP: { name: 'Guernsey Pound', countryCode: 'GG' },
  GHS: { name: 'Ghanaian Cedi', countryCode: 'GH' },
  GIP: { name: 'Gibraltar Pound', countryCode: 'GI' },
  GMD: { name: 'Gambian Dalasi', countryCode: 'GM' },
  GNF: { name: 'Guinean Franc', countryCode: 'GN' },
  GTQ: { name: 'Guatemalan Quetzal', countryCode: 'GT' },
  GYD: { name: 'Guyanaese Dollar', countryCode: 'GY' },
  HKD: { name: 'Hong Kong Dollar', countryCode: 'HK' },
  HNL: { name: 'Honduran Lempira', countryCode: 'HN' },
  HRK: { name: 'Croatian Kuna', countryCode: 'HR' },
  HTG: { name: 'Haitian Gourde', countryCode: 'HT' },
  HUF: { name: 'Hungarian Forint', countryCode: 'HU' },
  IDR: { name: 'Indonesian Rupiah', countryCode: 'ID' },
  ILS: { name: 'Israeli New Shekel', countryCode: 'IL' },
  IMP: { name: 'Manx Pound', countryCode: 'IM' },
  INR: { name: 'Indian Rupee', countryCode: 'IN' },
  IQD: { name: 'Iraqi Dinar', countryCode: 'IQ' },
  IRR: { name: 'Iranian Rial', countryCode: 'IR' },
  ISK: { name: 'Icelandic Króna', countryCode: 'IS' },
  JEP: { name: 'Jersey Pound', countryCode: 'JE' },
  JMD: { name: 'Jamaican Dollar', countryCode: 'JM' },
  JOD: { name: 'Jordanian Dinar', countryCode: 'JO' },
  JPY: { name: 'Japanese Yen', countryCode: 'JP' },
  KES: { name: 'Kenyan Shilling', countryCode: 'KE' },
  KGS: { name: 'Kyrgystani Som', countryCode: 'KG' },
  KHR: { name: 'Cambodian Riel', countryCode: 'KH' },
  KID: { name: 'Kiribati Dollar', countryCode: 'KI' },
  KMF: { name: 'Comorian Franc', countryCode: 'KM' },
  KRW: { name: 'South Korean Won', countryCode: 'KR' },
  KWD: { name: 'Kuwaiti Dinar', countryCode: 'KW' },
  KYD: { name: 'Cayman Islands Dollar', countryCode: 'KY' },
  KZT: { name: 'Kazakhstani Tenge', countryCode: 'KZ' },
  LAK: { name: 'Laotian Kip', countryCode: 'LA' },
  LBP: { name: 'Lebanese Pound', countryCode: 'LB' },
  LKR: { name: 'Sri Lankan Rupee', countryCode: 'LK' },
  LRD: { name: 'Liberian Dollar', countryCode: 'LR' },
  LSL: { name: 'Lesotho Loti', countryCode: 'LS' },
  LYD: { name: 'Libyan Dinar', countryCode: 'LY' },
  MAD: { name: 'Moroccan Dirham', countryCode: 'MA' },
  MDL: { name: 'Moldovan Leu', countryCode: 'MD' },
  MGA: { name: 'Malagasy Ariary', countryCode: 'MG' },
  MKD: { name: 'Macedonian Denar', countryCode: 'MK' },
  MMK: { name: 'Myanma Kyat', countryCode: 'MM' },
  MNT: { name: 'Mongolian Tugrik', countryCode: 'MN' },
  MOP: { name: 'Macanese Pataca', countryCode: 'MO' },
  MRU: { name: 'Mauritanian Ouguiya', countryCode: 'MR' },
  MUR: { name: 'Mauritian Rupee', countryCode: 'MU' },
  MVR: { name: 'Maldivian Rufiyaa', countryCode: 'MV' },
  MWK: { name: 'Malawian Kwacha', countryCode: 'MW' },
  MXN: { name: 'Mexican Peso', countryCode: 'MX' },
  MYR: { name: 'Malaysian Ringgit', countryCode: 'MY' },
  MZN: { name: 'Mozambican Metical', countryCode: 'MZ' },
  NAD: { name: 'Namibian Dollar', countryCode: 'NA' },
  NGN: { name: 'Nigerian Naira', countryCode: 'NG' },
  NIO: { name: 'Nicaraguan Cordoba', countryCode: 'NI' },
  NOK: { name: 'Norwegian Krone', countryCode: 'NO' },
  NPR: { name: 'Nepalese Rupee', countryCode: 'NP' },
  NZD: { name: 'New Zealand Dollar', countryCode: 'NZ' },
  OMR: { name: 'Omani Rial', countryCode: 'OM' },
  PAB: { name: 'Panamanian Balboa', countryCode: 'PA' },
  PEN: { name: 'Peruvian Sol', countryCode: 'PE' },
  PGK: { name: 'Papua New Guinean Kina', countryCode: 'PG' },
  PHP: { name: 'Philippine Peso', countryCode: 'PH' },
  PKR: { name: 'Pakistani Rupee', countryCode: 'PK' },
  PLN: { name: 'Polish Zloty', countryCode: 'PL' },
  PYG: { name: 'Paraguayan Guarani', countryCode: 'PY' },
  QAR: { name: 'Qatari Riyal', countryCode: 'QA' },
  RON: { name: 'Romanian Leu', countryCode: 'RO' },
  RSD: { name: 'Serbian Dinar', countryCode: 'RS' },
  RUB: { name: 'Russian Ruble', countryCode: 'RU' },
  RWF: { name: 'Rwandan Franc', countryCode: 'RW' },
  SAR: { name: 'Saudi Riyal', countryCode: 'SA' },
  SBD: { name: 'Solomon Islands Dollar', countryCode: 'SB' },
  SCR: { name: 'Seychellois Rupee', countryCode: 'SC' },
  SDG: { name: 'Sudanese Pound', countryCode: 'SD' },
  SEK: { name: 'Swedish Krona', countryCode: 'SE' },
  SGD: { name: 'Singapore Dollar', countryCode: 'SG' },
  SHP: { name: 'Saint Helena Pound', countryCode: 'SH' },
  SLE: { name: 'Sierra Leonean Leone', countryCode: 'SL' },
  SLL: { name: 'Sierra Leonean Leone', countryCode: 'SL' },
  SOS: { name: 'Somali Shilling', countryCode: 'SO' },
  SRD: { name: 'Surinamese Dollar', countryCode: 'SR' },
  SSP: { name: 'South Sudanese Pound', countryCode: 'SS' },
  STN: { name: 'Sao Tomean Dobra', countryCode: 'ST' },
  SYP: { name: 'Syrian Pound', countryCode: 'SY' },
  SZL: { name: 'Swazi Lilangeni', countryCode: 'SZ' },
  THB: { name: 'Thai Baht', countryCode: 'TH' },
  TJS: { name: 'Tajikistani Somoni', countryCode: 'TJ' },
  TMT: { name: 'Turkmenistani Manat', countryCode: 'TM' },
  TND: { name: 'Tunisian Dinar', countryCode: 'TN' },
  TOP: { name: 'Tongan Paʻanga', countryCode: 'TO' },
  TRY: { name: 'Turkish Lira', countryCode: 'TR' },
  TTD: { name: 'Trinidad and Tobago Dollar', countryCode: 'TT' },
  TVD: { name: 'Tuvaluan Dollar', countryCode: 'TV' },
  TWD: { name: 'New Taiwan Dollar', countryCode: 'TW' },
  TZS: { name: 'Tanzanian Shilling', countryCode: 'TZ' },
  UAH: { name: 'Ukrainian Hryvnia', countryCode: 'UA' },
  UGX: { name: 'Ugandan Shilling', countryCode: 'UG' },
  UYU: { name: 'Uruguayan Peso', countryCode: 'UY' },
  UZS: { name: 'Uzbekistani Som', countryCode: 'UZ' },
  VES: { name: 'Venezuelan Bolivar', countryCode: 'VE' },
  VND: { name: 'Vietnamese Dong', countryCode: 'VN' },
  VUV: { name: 'Vanuatu Vatu', countryCode: 'VU' },
  WST: { name: 'Samoan Tala', countryCode: 'WS' },
  XAF: { name: 'CFA Franc BEAC', countryCode: 'CM' }, // Central Africa region, using Cameroon as a representative
  XCD: { name: 'East Caribbean Dollar', countryCode: 'AG' }, // Eastern Caribbean, using Antigua and Barbuda as a representative
  XCG: { name: 'East Caribbean Guilder', countryCode: null }, // Not a real country code, set to null
  XDR: { name: 'Special Drawing Rights', countryCode: null }, // International, no country
  XOF: { name: 'CFA Franc BCEAO', countryCode: 'SN' }, // West Africa region, using Senegal as a representative
  XPF: { name: 'CFP Franc', countryCode: 'PF' }, // French Pacific territories, using French Polynesia
  YER: { name: 'Yemeni Rial', countryCode: 'YE' },
  ZAR: { name: 'South African Rand', countryCode: 'ZA' },
  ZMW: { name: 'Zambian Kwacha', countryCode: 'ZM' },
  ZWL: { name: 'Zimbabwean Dollar', countryCode: 'ZW' },
  // Cryptocurrencies or special cases
  ADA: { name: 'Cardano', countryCode: null }, // Cryptocurrency
};

export default currencyCountryMap;
